// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_3AEh-Dvtoh2pglEx-glgPc6nInJnXdE',
    appId: '1:70373331255:web:9feb6455109a7bc6f94ab2',
    messagingSenderId: '70373331255',
    projectId: 'philearnetr',
    authDomain: 'philearnetr.firebaseapp.com',
    storageBucket: 'philearnetr.appspot.com',
    measurementId: 'G-LCDSPSKZ8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgpABBGxVp4SnPpe3nq5IiGKq_HNxf78o',
    appId: '1:70373331255:android:681148c160a58edef94ab2',
    messagingSenderId: '70373331255',
    projectId: 'philearnetr',
    storageBucket: 'philearnetr.appspot.com',
  );
}
